name: Build & Release
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: "windows-2019"
    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: ./.github/actions/setup-go

      - run: go build ./cmd/dmverity-vhd
      - run: go build ./cmd/dmverity-vhd
        env:
          GOOS: linux
          GOARCH: amd64

      - uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: |
            dmverity-vhd.exe
            dmverity-vhd

  create_release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: binaries

      - name: Publish draft release
        uses: softprops/action-gh-release@v2.0.8
        with:
          prerelease: ${{ contains(github.ref, 'rc') }}
          files: |
            dmverity-vhd.exe
            dmverity-vhd
